ERROR = "ERROR"
NO_RESPONSE = "No response received"
EMPTY_ANSWER = "Empty answer"
RECEIVED = "Received"
FAILED = "Failed"
DATE_FORMAT = "%Y-%m-%d %H:%M:%S"
SOLID_BORDER = "SOLID"
FORMATTED_RESPONSE_TEMPLATE = [{
    "question": "",
    "answer": "",
    # "sources": []
}]
FORMATTED_RESPONSE_USAGE_TEMPLATE = [{
    "prompt_token": "",
    "output_token": "",
    "thinking_token": "",
    "total_token": ""
}]
NA = "N/A"
PRO_MODEL = "-pro"
MODEL_THINKING_BUDGET = 500

THINKING = "Thinking..."
GENERATING = "Generating..."

HARM_CATEGORY_HARASSMENT = "HARM_CATEGORY_HARASSMENT"
HARM_CATEGORY_HATE_SPEECH = "HARM_CATEGORY_HATE_SPEECH"
HARM_CATEGORY_SEXUALLY_EXPLICIT = "HARM_CATEGORY_SEXUALLY_EXPLICIT"
HARM_CATEGORY_DANGEROUS_CONTENT = "HARM_CATEGORY_DANGEROUS_CONTENT"

BLOCK_ONLY_HIGH = "BLOCK_ONLY_HIGH"
BLOCK_NONE = "BLOCK_NONE"
BLOCK_MEDIUM_AND_ABOVE = "BLOCK_MEDIUM_AND_ABOVE"
BLOCK_LOW_AND_ABOVE = "BLOCK_LOW_AND_ABOVE"

MAX_CONTEXT = 6
MAX_INPUT_TOKEN_LENGTH = 200
MAX_OUTPUT_TOKEN_LENGTH = None